### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by DanielAndreasen** [bhargaviparanjape/clickbait#1]
Hi Bhargavi,

I think this is a great job, and nice to see someone making the effort.
In order for other people to use it, you actually have to [choose an open source license](https://choosealicense.com/). Otherwise there are some legal issues.
I only realized you didn't have any after I used your data for [this](https://github.com/DanielAndreasen/clickbait-detector) much simpler version. This will not be used for anything other than a small project. Your repository is mentioned there in my README.md file.
I hope that is okay, otherwise just let me know.

Cheers,
Daniel

**Comment by abhijnanc** [comment]
Added. Thanks for pointing this.
